#!/bin/sh

# This script is to setup userena on dotcloud
python createdb.py
python superuser.py
python manage.py syncdb --settings=solesite.settings_dotcloud --noinput
python manage.py migrate --settings=solesite.settings_dotcloud
mkdir -p /home/dotcloud/data/media /home/dotcloud/volatile/static
python manage.py collectstatic --settings=solesite.settings_dotcloud --noinput
